In [1]:
import pandas as pd

In [4]:
youtube_df = pd.read_csv(r"C:\Users\Admin\final_capstone_project\filtered_youtube_data_abercrombie.csv")

In [8]:
youtube_df.describe()

              Views         Likes    Comments
count  9.000000e+00      9.000000     9.00000
mean   3.726376e+05   5356.888889  1160.00000
std    4.113540e+05   5548.782399  1167.45032
min    5.345000e+03     63.000000    18.00000
25%    5.341700e+04    721.000000   427.00000
50%    9.387400e+04   4798.000000   618.00000
75%    6.283910e+05   9484.000000  2148.00000
max    1.147115e+06  16335.000000  3149.00000

In [9]:
youtube_df

,Title,Views,Likes,Comments,Published Date,Video ID
0,Ex- Abercrombie & Fitch CEO charged with sex t...,581749,5070,2676,2024-10-23T06:06:10Z,RMu9cZ0znZE
1,White Hot: The Rise & Fall of Abercrombie & Fi...,1147115,16335,2148,2022-03-31T17:30:00Z,3yperp-SFYM
2,Ex-Abercrombie & Fitch CEO Raped Male Models D...,628391,9808,3149,2024-10-22T23:30:03Z,KmYgmagq7Ic
3,Former Abercrombie & Fitch CEO Accused of Sex ...,78472,1459,548,2024-10-22T21:54:37Z,8EiVOd9_zN4
4,Ex-Abercrombie & Fitch CEO among 3 arrested fo...,33765,474,214,2024-10-22T16:26:40Z,LqC8eHPkdsc
5,Abercrombie & Fitch - The Rise and Fall...And ...,93874,4798,642,2024-09-11T18:00:03Z,jHeDN8wiiwo
6,An update on the Abercrombie & Fitch sex traff...,5345,63,18,2024-12-04T00:29:34Z,FcsX1-Iwins
7,Why Abercrombie & Fitch’s Stock Exploded Faste...,731610,9484,427,2024-07-08T14:00:12Z,FvE1YOxtMaM
8,Former CEO of Abercrombie & Fitch indicted on ...,53417,721,618,2024-10-22T19:15:00Z,75c-nXK7VSc

In [12]:
youtube_df["Published Date"] = pd.to_datetime(youtube_df["Published Date"])
youtube_df.dtypes

Title                          object
Views                           int64
Likes                           int64
Comments                        int64
Published Date    datetime64[ns, UTC]
Video ID                       object
dtype: object